version: "3.8"
services:
  movies-back:
    image: movies-back:latest
    build:
      context: ./back/movies-back
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE_HOST: "mysql-db"
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    networks:
      - movies
  mysql-db:
    image: hsheth2/mysql-low-memory:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db_cinema"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - movies
  frontend:
    image: frontend:latest
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 80:80
    networks:
      - movies
volumes:
  mysql-db:
networks:
  movies:
