version: "3.8"
services:
  movies-back:
    image: movies-back:latest
    build:
      context: ./back/movies-back
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE_HOST: "mysql-db"
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    networks:
      - movies
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db_cinema"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - movies
  image-storage:
    image: file-server:v1
    build:
      context: ./back/file-server
      dockerfile: Dockerfile
    restart: always
    #    environment:
    #      _JAVA_OPTIONS: >
    #        -Xdebug
    #        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - 8090:8090
      - 5005:5005
    networks:
      - movies
  frontend:
    image: frontend:latest
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - movies
volumes:
  mysql-db:
networks:
  movies:
