version: '3.8'
services:
  movies-back:
    image: movies-back:latest
    build:
      context: ./movies-back
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE_HOST: 'mysql-db'
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    networks:
      - movies
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db_cinema'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - movies
volumes:
  mysql-db:
networks:
  movies: